-- Letzte IFGK-Sätze mit Fehler-/Statusinformationen
SELECT
    IFGKTSTP,
    IFGKIFFI,
    IFGKIFNR,
    IFGKIFST,
    IFGKIFKO,
    IFGKIFPO,
    IFGKFENR,
    IFGKFFLD,
    IFGKAGJJ,
    IFGKAGNR,
    IFGKUEDA,
    IFGKUEUZ
FROM TVPFTEST.IFGK
WHERE IFGKFENR <> ''
   OR IFGKIFST <> '00'
ORDER BY IFGKTSTP DESC
FETCH FIRST 100 ROWS ONLY;

-- Positionsfehler
SELECT
    IFGPIFGK,
    IFGPIFGP,
    IFGPIFFI,
    IFGPIFNR,
    IFGPIFST,
    IFGPIFPO,
    IFGPFENR,
    IFGPFFLD,
    IFGPTENR,
    IFGPAGJJ,
    IFGPAGNR,
    IFGPAGPO
FROM TVPFTEST.IFGP
WHERE IFGPFENR <> ''
ORDER BY IFGPTSTP DESC
FETCH FIRST 100 ROWS ONLY;
